BE.Web/Models/AccountLoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class AccountLoginModel
    {
        public string username { get; set; }
        public string password { get; set; }
    }
}

BE.Web/Models/BlogModel.cs
using BE.Repo;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class BlogModel
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Image")]
        public string ThumnailImageName { get; set; }

        [Display(Name = "Content")]
        public string Content { get; set; }

        [Display(Name = "CreatedDate")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "UpdatedDate")]
        public DateTime UpdatedDate { get; set; }

        public Category Category { get; set; }

        public IEnumerable<Comment> Commnents { get; set; }

        public IEnumerable<BlogImage> BlogImages { get; set; }

    }
}

BE.Web/Models/BlogPostModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class BlogPostModel
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "CategoryId")]
        public int CategoryId { get; set; }

        [Display(Name = "Content")]
        public string Content { get; set; }

        [Display(Name = "Content")]
        public string ThumnailImageName { get; set; }
    }
}

BE.Web/Models/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class CategoryModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Content { get; set; }

        public ICollection<BlogModel> Blogs { get; set; }

        public int BlogsCount { get { return Blogs.Count; } }

    }
}

BE.Web/Models/CategoryPostModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class CategoryPostModel
    {
        [Required]
        public string Content { get; set; }
    }
}

BE.Web/Models/CommentModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BE.Web.Models
{
    public class CommentModel
    {
        public int Id { get; set; }
            
        [Required]
        public string Content { get; set; }

        public int BlogId { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}

BE.Web/Models/ErrorViewModel.cs
using System;

namespace BE.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BE.Web/Models/PostCommentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BA.Web.Models
{
    public class PostCommentModel
    {
        public int BlogId { get; set; }
        public string Content { get; set; }
    }
}

BE.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BE.Repo;
using BE.Service;
using BE.Web.Helpers;
using BE.Web.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace BE.Web.Controllers
{
    public class BlogController : Controller
    {

        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;

        public BlogController(IBlogService blogService, IMapper mapper)
        {
            this._blogService = blogService;
            this._mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            var blogs = await _blogService.GetLatestBlogs();

            var blogsModel = _mapper.Map<IEnumerable<BlogModel>>(blogs);

            int pageSize = 6;

            return View(await PaginatedList<BlogModel>.CreateAsync(blogsModel, page ?? 1, pageSize));
        }

        public async Task<IActionResult> Details(int id, string slug)
        {
            var blog = await _blogService.GetBlog(id);

            if (blog == null || slug != SlugGenerator.ToSlug(blog.Title))
            {
                return NotFound();
            }

            var blogModel = _mapper.Map<BlogModel>(blog);

            return View(blogModel);
        }

    }
}

BE.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BE.Service;
using BE.Web.Helpers;
using BE.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace BE.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;

        public CategoryController(ICategoryService categoryService, IBlogService _blogService, IMapper mapper)
        {
            this._categoryService = categoryService;
            this._blogService = _blogService;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index(int id, string slug, int? page = 1)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var category = await _categoryService.GetCategoryById(id);

            if (slug != SlugGenerator.ToSlug(category.Content) || category == null)
            {
                return NotFound();
            }

            var categoryModel = _mapper.Map<CategoryModel>(category);

            ViewBag.CurrentCategory = categoryModel.Content;

            int pageSize = 6;

            return View(await PaginatedList<BlogModel>.CreateAsync(categoryModel.Blogs, page ?? 1, pageSize));
        }
    }
}

BE.Web/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BE.Repo;
using BE.Service;
using BE.Web.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BE.Web.Controllers
{
    public class CommentController : Controller
    {

        private readonly ICommentService _commentService;
        private readonly IMapper _mapper;

        public CommentController(ICommentService commentService, IMapper mapper)
        {
            this._commentService = commentService;
            this._mapper = mapper;
        }

        [HttpPost]
        public async Task<JsonResult> Create(CommentModel comment)
        {

            var commentEntity = _mapper.Map<Comment>(comment);

            var commentResult = await _commentService.CreateComment(commentEntity);

            string strDatetime = String.Format("{0:G}", commentResult.CreatedDate);
            commentResult.CreatedDate = DateTime.Parse(strDatetime);

            return Json(new { comment = commentResult, accountName = "Anonymous" });

        }
    }
}

BE.Web/Views/Blog/Details.cshtml
@using BE.Web.Helpers;

@model BE.Web.Models.BlogModel;


@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8">
            <div class="container">
                <div class="post-single">
                    <div class="post-details">

                        <h1>@Model.Title<a href="#"></a></h1>
                        <div class="post-footer d-flex align-items-center flex-column flex-sm-row">
                            <a href="#" class="author d-flex align-items-center flex-wrap">
                                <div class="title"><strong>Author: </strong>Admin</div>
                            </a>
                            <div class="d-flex align-items-center flex-wrap">
                                <div class="date" style="float:right;"><i class="icon-clock"></i> @Model.CreatedDate</div>
                                <div class="comments meta-last"><i class="icon-comment"></i><span class="comment-count">@Model.Commnents.Count()</span></div>
                            </div>
                        </div>
                        <div class="post-body">
                            @Html.Raw(Model.Content)
                        </div>
                        <hr />

                        <div class="post-comments">
                            <header>
                                <h3 class="h6">Post Comments<span class="no-of-comments">(<span class="comment-count">@Model.Commnents.Count()</span>)</span></h3>
                            </header>
                            @if (Model.Commnents.Count() > 0)
                            {
                                foreach (var comment in Model.Commnents)
                                {
                                    <div class="comment">
                                        <div class="comment-header d-flex justify-content-between">
                                            <div class="user d-flex align-items-center">
                                                <div class="title"><strong>Anonymous</strong><span class="date">@comment.CreatedDate</span></div>
                                            </div>
                                        </div>
                                        <div class="comment-body">
                                            <p>@comment.Content</p>
                                        </div>
                                    </div>
                                }
                            }

                        </div>
                        <div class="add-comment">
                            <header>
                                <h3 class="h6">Leave a comment </h3>
                            </header>
                            <span style="color:red; display:none;" class="comment-error-message"></span>
                            <form action="#" class="commenting-form">
                                <div class="row">
                                    <input name="BlogId" type="hidden" class="form-control" value="@Model.Id" />
                                    <div class="form-group col-md-12">
                                        <textarea name="Content" id="usercomment" placeholder="Type your comment" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button type="submit" class="btn btn-secondary btn-comment">Submit Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        
    </div>
</div>

@section Scripts{




    <script>



        function RenderHtml(comment) {

            var htmlComment = '<div style="display:none;" class="comment"><div class="comment-header d-flex justify-content-between">'
            htmlComment += ' <div class="user d-flex align-items-center">';
            htmlComment += '  <div class="title"><strong>' + comment.accountName + '</strong > <span class="date">' + comment.comment.createdDate + '</span></div > ';
            htmlComment += ' </div> </div><div class="comment-body"><p>' + comment.comment.content + '</p></div></div>';

            $('.post-comments').append(htmlComment);
            $('.comment').fadeIn('slow');

            IncreaseNumberOfComment();

        }

        function IncreaseNumberOfComment() {
            var currentCommentCount = $('.comment-count').first().text();

            currentCommentCount++;

            $('.comment-count').text(currentCommentCount);
        }

        $('.btn-comment').on('click', function (e) {
            e.preventDefault();

            var data = $('form').serialize();

            $.ajax({
                type: 'POST',
                url: '/Comment/Create',
                dataType: 'json',
                contentType: 'application/x-www-form-urlencoded; charset=utf-8',
                data: data,
                success: function (result) {
                    RenderHtml(result);
                    $('#usercomment').val('');
                },
                error: function (jqXHR) {


                    if (jqXHR.status == 400) {
                        $('.comment-error-message').text('');
                        $('.comment-error-message').text(jqXHR.responseJSON.message);
                        $('.comment-error-message').fadeIn().delay(1000).fadeOut('slow');
                    }

                    if (jqXHR.status == 401) {
                        $('.comment-error-message').text('');
                        $('.comment-error-message').text(jqXHR.responseJSON.message);
                        $('.comment-error-message').fadeIn().delay(1000).fadeOut('slow');
                    }
                }


            });

        });


    </script>


}

BE.Web/Views/Blog/Index.cshtml
@using BE.Web.Helpers;

@model PaginatedList<BE.Web.Models.BlogModel>

@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currentPage = ViewContext.RouteData.Values["page"] == null ? 1 : ViewContext.RouteData.Values["page"];
}

<div class="container" style="max-width:80%;">
    <div class="row">
        <div class="col-lg-3">
            <aside>
                <!-- Widget [Categories Widget]-->
                <div class="widget categories">
                    <header>
                        <h3 class="h6">Categories</h3>
                    </header>
                    @await Component.InvokeAsync("Category")
                </div>
            </aside>
        </div>
        <div class="col-lg-9">
            <section class="featured-posts no-padding-top">
                <div class="container2">
                    @foreach (var item in Model)
                    {
                        <div class="row d-flex align-items-stretch" style="margin-top:10px">
                            <div class="text col-lg-7">
                                <div class="text-inner d-flex align-items-center">
                                    <div class="content">
                                        <header class="post-header">
                                            <div class="category">
                                                <a asp-controller="Category" asp-route-id="@item.Category.Id" asp-route-slug="@SlugGenerator.ToSlug(item.Category.Content)" asp-route-page="1">@item.Category.Content</a>
                                            </div>
                                            <a asp-action="Details" asp-route-id="@item.Id" asp-route-slug="@SlugGenerator.ToSlug(item.Title)">
                                                <h2 class="h4">@item.Title</h2>
                                            </a>
                                        </header>

                                        <p>@HtmlRender.Truncate(item.Content, 200)</p>
                                        <footer class="post-footer d-flex align-items-center">
                                            <a href="#" class="author d-flex align-items-center flex-wrap">
                                                @*<div class="avatar"><img src="img/avatar-1.jpg" alt="..." class="img-fluid"></div>*@
                                                <div class="title"><span>Nhan Ngo</span></div>
                                            </a>
                                            <div class="date"><i class="icon-clock"></i>@item.CreatedDate.Date.ToString("MMM dd yyyy")</div>
                                            <div class="comments"><i class="icon-comment"></i>@item.Commnents.Count()</div>
                                        </footer>
                                    </div>
                                </div>
                            </div>
                            <div class="image col-lg-5"><img src="/images/@item.ThumnailImageName" alt="..."></div>
                        </div>
                    }
                </div>
            </section>

        </div>
    </div>
</div>


@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<center>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</center>

BE.Web/Views/Category/Index.cshtml
@using BE.Web.Helpers;

@model PaginatedList<BE.Web.Models.BlogModel>

@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currentPage = ViewContext.RouteData.Values["page"] == null ? 1 : ViewContext.RouteData.Values["page"];
}
<div style="margin-left:40%;">
    <h4>@ViewData["CurrentCategory"]</h4>
</div>
<div class="container" style="max-width:80%;">
    <div class="row">
        <div class="col-lg-3">
            <aside>
                <!-- Widget [Categories Widget]-->
                <div class="widget categories">
                    <header>
                        <h3 class="h6">Categories</h3>
                    </header>
                    @await Component.InvokeAsync("Category")
                </div>
            </aside>
        </div>
        <div class="col-lg-9">
            <section class="featured-posts no-padding-top">
                <div class="container2">
                    @foreach (var item in Model)
                    {
                        <div class="row d-flex align-items-stretch">
                            <div class="text col-lg-7">
                                <div class="text-inner d-flex align-items-center">
                                    <div class="content">
                                        <header class="post-header">
                                            <div class="category">
                                                <a asp-controller="Category" asp-route-id="@item.Category.Id" asp-route-slug="@SlugGenerator.ToSlug(item.Category.Content)" asp-route-page="1">@item.Category.Content</a>
                                            </div>
                                            <a asp-controller="Blog" asp-action="Details" asp-route-id="@item.Id" asp-route-slug="@SlugGenerator.ToSlug(item.Title)">
                                                <h2 class="h4">@item.Title</h2>
                                            </a>
                                        </header>

                                        <p>@HtmlRender.Truncate(item.Content, 200)</p>
                                        <footer class="post-footer d-flex align-items-center">
                                            <a href="#" class="author d-flex align-items-center flex-wrap">
                                                @*<div class="avatar"><img src="img/avatar-1.jpg" alt="..." class="img-fluid"></div>*@
                                                <div class="title"><span>Nhan Ngo</span></div>
                                            </a>
                                            <div class="date"><i class="icon-clock"></i>@item.CreatedDate.Date.ToString("MMM dd yyyy")</div>
                                            <div class="comments"><i class="icon-comment"></i>@item.Commnents.Count()</div>
                                        </footer>
                                    </div>
                                </div>
                            </div>
                            <div class="image col-lg-5"><img src="/images/@item.ThumnailImageName" alt="..."></div>
                        </div>
                    }
                </div>
            </section>

        </div>
    </div>
</div>


@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<center>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</center>

BE.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BE.Web/Views/Shared/Components/Category/Default.cshtml
@model IEnumerable<BE.Web.Models.CategoryModel>
@using BE.Web.Helpers;

@if (@Model.Count() > 0)
{
    var defaultCurrentPage = 1;
    @foreach (var item in @Model)
    {
        <div class="item d-flex justify-content-between"><a asp-controller="Category" asp-route-id="@item.Id" asp-route-slug="@SlugGenerator.ToSlug(item.Content)" asp-route-page="@defaultCurrentPage">@item.Content</a><span>@item.BlogsCount</span></div>
    }
}

BE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

        <!-- Font Awesome CSS-->
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <!-- Custom icon font-->
        <link rel="stylesheet" href="~/css/fontastic.css" />
        <!-- Google fonts - Open Sans-->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
        <!-- Fancybox-->
        <link rel="stylesheet" href="~/lib/fancyapps/fancybox/jquery.fancybox.min.css" />
        <!-- theme stylesheet-->
        <link rel="stylesheet" href="~/css/style.default.css" id="theme-stylesheet" />
        <!-- Custom stylesheet - for your changes-->
        <link rel="stylesheet" href="~/css/custom.css" />

        @RenderSection("Styles", required: false)


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>



    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->


</head>
<body>
    @{
        var host = ViewContext.HttpContext.Request.Host;
        var imgUrl = host + "/images/hero.jpg";
    }
    <header class="header">
        <!-- Main Navbar-->
        <nav class="navbar navbar-expand-lg">

            <div class="container">
                <!-- Navbar Brand -->
                <div class="navbar-header d-flex align-items-center justify-content-between">
                    <!-- Navbar Brand --><a asp-action="Index" asp-controller="Blog" class="navbar-brand">BLOG</a>
                    <!-- Toggle Button-->
                    <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
                </div>
                <!-- Navbar Menu -->
                <div id="navbarcollapse" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Blog" class="nav-link active ">Home</a>
                        </li>
                    </ul>


                </div>
            </div>
        </nav>
    </header>

    <!-- Intro Section-->
    <section style="background: url(/images/hero.jpg); background-size: cover; background-position: center center" class="hero">
        <div class="container">
            <div class="row">
                <h1>
                    <span>Welcome to Blog Engine</span>
                </h1>
            </div>
        </div>
    </section>

    <br />

    @RenderBody()



    <footer class="main-footer">
        <div class="copyrights">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; 2017. All rights reserved. Your great site.</p>
                    </div>
                    <div class="col-md-6 text-right">
                        <p>
                            Template By <a href="https://bootstraptemple.com" class="text-white">Bootstrap Temple</a>
                            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>*@


        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery.cookie/jquery.cookie.js"></script>
        <script src="~/lib/fancyapps/fancybox/jquery.fancybox.min.js"></script>
        <script src="~/js/front.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>